name: security
on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
        with:
          go-version: "1.22"
      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
      - uses: github/codeql-action/init@45775bd8235c68ba998cffa5171334d58593da47
        with:
          languages: go
      - uses: github/codeql-action/autobuild@45775bd8235c68ba998cffa5171334d58593da47
      - uses: github/codeql-action/analyze@45775bd8235c68ba998cffa5171334d58593da47
